"use strict";

var CategoryXML = function(){
    
};

CategoryXML.getXML = function(year){
    var s = '<name>spelling_sow_y{{YEAR}}</name>'
    + '<activated>1</activated>'
    + '<beta>1</beta>'
    + '<languages>'
    + '<en_gb>'
    + '<title>Year {{YEAR}}</title>'
    + '<description/>'
    + '<keywords/>'
    + '<yeargroups/>'
    + '<presentation/>'
    + '<iconfilename>spelling-_year_{{YEAR}}_icon-en_gb.png</iconfilename>'
    + '<imagefilename>spelling-_year_{{YEAR}}_help-en_gb.png</imagefilename>'
    + '<largeiconimage/>'
    + '</en_gb>'
    + '</languages>'
    + '<imagemarkers>[]</imagemarkers>'
    + '<sections>'
    + '<section>'
    + '<name>overview and assesment</name>'
    + '<hidename>0</hidename>'
    + '<date_from/>'
    + '<date_to/>'
    + '<type/>'
    + '<activated>1</activated>'
    + '<free_text_pos>1</free_text_pos>'
    + '<use_large_icons>0</use_large_icons>'
    + '<section_style/>'
    + '<frontscreenversion/>'
    + '<translations>'
    + '<en_gb>'
    + '<title>Overview and guide </title>'
    + '<free_text/>'
    + '</en_gb>'
    + '</translations>'
    + '<links>'
    + '<application fromdate="" todate="">guides/Year{{YEAR}}_spelling_overview</application>'
    + '</links>'
    + '</section>'
    + '<section>'
    + '<name>Autumn 1 </name>'
    + '<hidename>0</hidename>'
    + '<date_from/>'
    + '<date_to/>'
    + '<type/>'
    + '<activated>1</activated>'
    + '<free_text_pos>1</free_text_pos>'
    + '<use_large_icons>0</use_large_icons>'
    + '<section_style/>'
    + '<frontscreenversion/>'
    + '<translations>'
    + '<en_gb>'
    + '<title>Autumn 1 </title>'
    + '<free_text/>'
    + '</en_gb>'
    + '</translations>'
    + '<links>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn1_Week1_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk1_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk1_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn1_Week2_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk2_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk2_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn1_Week3_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk3_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk3_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn1_Week4_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk4_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk4_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn1_Week5_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk5_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk5_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn1_Week6_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk6_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut1_Wk6_LSCWC</application>'
    + '</links>'
    + '</section>'
    + '<section>'
    + '<name>Autumn 2</name>'
    + '<hidename>0</hidename>'
    + '<date_from/>'
    + '<date_to/>'
    + '<type/>'
    + '<activated>1</activated>'
    + '<free_text_pos>1</free_text_pos>'
    + '<use_large_icons>0</use_large_icons>'
    + '<section_style/>'
    + '<frontscreenversion/>'
    + '<translations>'
    + '<en_gb>'
    + '<title>Autumn 2</title>'
    + '<free_text/>'
    + '</en_gb>'
    + '</translations>'
    + '<links>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn2_Week1_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk1_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk1_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn2_Week2_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk2_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk2_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn2_Week3_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk3_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk3_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn2_Week4_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk4_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk4_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn2_Week5_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk5_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk5_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Autumn2_Week6_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk6_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Aut2_Wk6_LSCWC</application>'
    + '</links>'
    + '</section>'
    + '<section>'
    + '<name>Spring 1</name>'
    + '<hidename>0</hidename>'
    + '<date_from/>'
    + '<date_to/>'
    + '<type/>'
    + '<activated>1</activated>'
    + '<free_text_pos>1</free_text_pos>'
    + '<use_large_icons>0</use_large_icons>'
    + '<section_style/>'
    + '<frontscreenversion/>'
    + '<translations>'
    + '<en_gb>'
    + '<title>Spring 1</title>'
    + '<free_text/>'
    + '</en_gb>'
    + '</translations>'
    + '<links>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring1_Week1_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk1_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk1_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring1_Week2_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk2_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk2_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring2_Week3_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk3_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk3_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring1_Week4_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk4_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk4_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring1_Week5_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk5_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk5_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring1_Week6_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk6_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr1_Wk6_LSCWC</application>'
    + '</links>'
    + '</section>'
    + '<section>'
    + '<name>Spring 2</name>'
    + '<hidename>0</hidename>'
    + '<date_from/>'
    + '<date_to/>'
    + '<type/>'
    + '<activated>1</activated>'
    + '<free_text_pos>1</free_text_pos>'
    + '<use_large_icons>0</use_large_icons>'
    + '<section_style/>'
    + '<frontscreenversion/>'
    + '<translations>'
    + '<en_gb>'
    + '<title>Spring 2</title>'
    + '<free_text/>'
    + '</en_gb>'
    + '</translations>'
    + '<links>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring2_Week1_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk1_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk1_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring2_Week2_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk2_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk2_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring2_Week3_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk3_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk3_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring2_Week4_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk4_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk4_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring2_Week5_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk5_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk5_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Spring2_Week6_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk6_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Spr2_Wk6_LSCWC</application>'
    + '</links>'
    + '</section>'
    + '<section>'
    + '<name>Summer 1</name>'
    + '<hidename>0</hidename>'
    + '<date_from/>'
    + '<date_to/>'
    + '<type/>'
    + '<activated>1</activated>'
    + '<free_text_pos>1</free_text_pos>'
    + '<use_large_icons>0</use_large_icons>'
    + '<section_style/>'
    + '<frontscreenversion/>'
    + '<translations>'
    + '<en_gb>'
    + '<title>Summer 1</title>'
    + '<free_text/>'
    + '</en_gb>'
    + '</translations>'
    + '<links>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer1_Week1_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk1_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk1_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer1_Week2_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk2_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk2_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer1_Week3_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk3_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk3_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer1_Week4_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk4_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk4_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer1_Week5_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk5_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk5_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer1_Week6_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk6_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum1_Wk6_LSCWC</application>'
    + '</links>'
    + '</section>'
    + '<section>'
    + '<name>Summer 2</name>'
    + '<hidename>0</hidename>'
    + '<date_from/>'
    + '<date_to/>'
    + '<type/>'
    + '<activated>1</activated>'
    + '<free_text_pos>1</free_text_pos>'
    + '<use_large_icons>0</use_large_icons>'
    + '<section_style/>'
    + '<frontscreenversion/>'
    + '<translations>'
    + '<en_gb>'
    + '<title>Summer 2</title>'
    + '<free_text/>'
    + '</en_gb>'
    + '</translations>'
    + '<links>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer2_Week1_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk1_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk1_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer2_Week2_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk2_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk2_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer2_Week3_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk3_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk3_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer2_Week4_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk4_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk4_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer2_Week5_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk5_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk5_LSCWC</application>'
    + '<application fromdate="" todate="">diyjs/y{{YEAR}}_Summer2_Week6_Week</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk6_Dictation</application>'
    + '<application fromdate="" todate="">guides/Spelling_Y{{YEAR}}_Sum2_Wk6_LSCWC</application>'
    + '</links>'
    + '</section>'
    + '</sections>';
    
    return s.replace(/{{YEAR}}/g, year);
    
};

module.exports = CategoryXML;




/*


   
   
   
   
   */

